name: GitHub Stats

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install -g github-stats

      - name: Gerar estatísticas
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          github-stats --token $GH_TOKEN --output stats.svg

      - name: Commit e push das mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg STATS.md
          git commit -m "Atualizar estatísticas"
          git push
