name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:  # Permite rodar manualmente
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: yuricapella  # Substitua pelo seu usuário do GitHub
          template: classic
          base: header, repositories
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage, bytes-size
          plugin_contributions: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_traffic: yes
          output: github-metrics.svg

      - name: Commit e push do SVG gerado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add github-metrics.svg
          git commit -m "Atualizar métrica do GitHub" || echo "Nada para atualizar"
          git push
