name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Obter estatísticas do GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.METRICS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/users/${{ github.repository_owner }} > stats.json

      - name: Gerar estatísticas formatadas (STATS.md)
        run: |
          jq -r '"Stars: " + (.public_repos|tostring) + "\n" +
                "Forks: " + (.followers|tostring) + "\n" +
                "All-time contributions: " + (.public_gists|tostring) + "\n" +
                "Lines of code changed: " + (.disk_usage|tostring) + "\n" +
                "Repositories with contributions: " + (.total_private_repos|tostring)' stats.json > STATS.md

      - name: Gerar imagem das estatísticas (github-metrics.svg)
        run: |
          node -e "
          const fs = require('fs');
          const stats = JSON.parse(fs.readFileSync('stats.json'));
          const svgContent = \`
          <svg width='600' height='300' xmlns='http://www.w3.org/2000/svg'>
            <style>
              .title { fill: #ffffff; font-size: 24px; font-family: Arial, sans-serif; }
              .stat { fill: #ffffff; font-size: 18px; font-family: Arial, sans-serif; }
              .icon { font-size: 18px; }
            </style>
            <rect width='100%' height='100%' fill='#24292e'/>
            <text x='20' y='40' class='title'>GitHub Statistics</text>
            <text x='20' y='80' class='stat'>★ Stars: \${stats.public_repos}</text>
            <text x='20' y='110' class='stat'>⑂ Forks: \${stats.followers}</text>
            <text x='20' y='140' class='stat'>✎ All-time contributions: \${stats.public_gists}</text>
            <text x='20' y='170' class='stat'>↺ Lines of code changed: \${stats.disk_usage}</text>
            <text x='20' y='200' class='stat'>☰ Repositories with contributions: \${stats.total_private_repos}</text>
          </svg>\`;
          fs.writeFileSync('github-metrics.svg', svgContent);
          "

      - name: Commit e push das estatísticas
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add STATS.md github-metrics.svg
          git commit -m "Atualizar estatísticas do GitHub" || echo "Nada para atualizar"
          git push
